version: "3"
services:
  webproxy:
    image: "nginx"
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 7655:80
    networks:
      - frontend
      - backend
  frontend:
    build:
      context: "frontend"
      dockerfile: Dockerfile
    restart: unless-stopped
#    ports:
#      - "8081:80"
    networks:
      - frontend
  backend:
    build:
      context: "backend"
      dockerfile: Dockerfile
    restart: unless-stopped
#    ports:
#      - "3000:3000"
    networks:
      - backend
  db:
    image: "mongo"
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    networks:
      - backend
volumes:
  mongodata:
    external: false
  mongoconfig:
    external: false

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge